site:
  about:
    siteName: Orchid Writers' Blocks
    siteDescription: A collection of Template Tags and Components that help you get past the writer's block and make building your site a dream.

theme:
  primaryColor: '#4C376C'
  social:
    github: 'JavaEden/Orchid'

