sourceDirs:
  - '../../main/kotlin'
  - '../../main/java'

classPages:
  menu:
    - type: 'separator'
      title: 'Class Info'
      order: 100
    - type: 'kotlindocClassLinks'
      includeItems: true
      order: 110
