key: FutureImperfect
theme:
  isolated: true
sidebar:
  - type: recentPosts
    limit: 3
    noWrapper: true
    template: 'includes/postPreview_mini'
  - type: recentPosts
    limit: 5
    noWrapper: true
    template: 'includes/postPreview_list'
legacySearch: false
